
source 'https://github.com/CocoaPods/Specs.git'

target 'CoreSDKDemo' do
    
pod 'LJLogView', '~> 1.0.0'
    
pod 'DroiCoreSDK'
    post_install do |installer|
        require './Pods/DroiCoreSDK/scripts/postInstall.rb'
        DroiCoreParser.installParser()
    end
end