source 'https://github.com/CocoaPods/Specs.git'

target 'DroiAnalyticsDemo' do

pod 'DroiAnalyticsSDK'
pod 'DroiCoreSDK'
post_install do |installer|
    require './Pods/DroiCoreSDK/scripts/postInstall.rb'
    DroiCoreParser.installParser()
end
end